server:
  port: 30


spring:
  application:
    name: cloud-consul-consumer-order
  cloud:
    consul:
      host: 192.168.6.10
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
