server:
  port: 2001

spring:
  application:
    name: cloud-eureka-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  zipkin:
    base-url: http://192.168.6.10:9411
  sleuth:
    sampler:
      # 采样率在0-1之间
      probability: 1
eureka:
  client:
    # 表示将自己注册进eureka
    register-with-eureka: true
    # 获取注册表
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://eureka1003.com:1003/eureka/
      # 集群版
      #defaultZone: http://eureka1001.com:1001/eureka/,http://eureka1002.com:1002/eureka/
  instance:
    # 实例ID
    instance-id: payment2001
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    # eureka 客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 1
    # eureka 服务端在收到最后一次心跳的等待时间上线
    lease-expiration-duration-in-seconds: 2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itguigu.springcloud.entities



