server:
  port: 7001

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darren88881/sprincloud-config.git #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - springcloud-config
      label: master #读取分支
  #rabbitmq相关配置
  rabbitmq:
    host: 192.168.6.8
    port: 5672
    username: admin
    password: 123


eureka:
  client:
    service-url:
      defaultZone: http://eureka1003.com:1003/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点 SpringCloud Bus动态刷新全局广播
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


