server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.10:8848 #配置Nacos地址

#端口暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'