server:
  port: 40

eureka:
  client:
    register-with-eureka: false # 不注册进eureka服务中心
    service-url:
      #defaultZone: http://eureka1001.com:1001/eureka/,http://eureka1002.com:1002/eureka/
      # 单机版
      defaultZone: http://eureka1003.com:1003/eureka/

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下, 两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.itguigu.springcloud.service.PaymentFeignService: debug