server:
  port: 20

spring:
  application:
    name: cloud-eureka-consumer-order

eureka:
  client:
    # 表示将自己注册进eureka
    register-with-eureka: true
    # 获取注册表
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://eureka1003.com:1003/eureka
      # 集群版
      # defaultZone: http://eureka1001.com:1001/eureka/,http://eureka1002.com:1002/eureka/