server:
  port: 1003

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    hostname: eureka1003.com
  client:
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    #表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka1003.com:1003/eureka/
  server:
    #关闭自我保护机制，保证不可用服务立即被踢出
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
