server:
  port: 10001

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.10:1111 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.6.10:8080 #配置Sentinel dashboard地址
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口置
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: '*'