server:
  port: 10004

spring:
  application:
    name: sentinel-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.10:1111 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'